language: php

php:
 - 5.4
 - 5.5
 - 5.6
 - 7.0
 - 7.1

before_script:
 - composer self-update || true
 - composer install --no-interaction --no-progress --no-suggest --optimize-autoloader

script: vendor/bin/phpunit